sonar.projectKey=calitrack-backend
sonar.projectName=CaliTrack Backend
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=**/target/**
