spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/calitrack}
    username: ${SPRING_DATASOURCE_USERNAME:calitrack}
    password: ${SPRING_DATASOURCE_PASSWORD:calitrack}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
