spring:
  application:
    name: calitrack-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/calitrack
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
supabase:
  url: https://uzyjygnqzrfxgnijiufd.supabase.co
  jwt:
    issuer: https://uzyjygnqzrfxgnijiufd.supabase.co/auth/v1
    audience: authenticated
    jwk-set-uri: https://uzyjygnqzrfxgnijiufd.supabase.co/auth/v1/.well-known/jwks.json
